### ISSUE TITLE
Highlights as Blockquotes in Markdown Export

### ISSUE THREAD

**Issue by paulhdk** [pch/kindle-formatter#3]
Hi! 

First of all, brilliant idea and app!

I was wondering wether it would be possible to have the highlights themselves be blockquotes in the plain text markdown export?

I thought it might be possible via the custom template functionality, but didn't figure out how to do it.

Many thanks!

**Comment by pch** [comment]
Hi @PBHDK 

Yes, it's possible using the custom template and markdown quotes (`> quote`). Here's a template you might try:

```markdown
- Title:: {{title}}
- Authors:: {{authors}}

- **Highlights and Notes**
{{#sections}}

## {{sectionTitle}}
{{#highlights}}
> {{highlight}}

**{{type}}** {{#page}}page: {{page}}.{{/page}} {{#location}}location: {{location}}{{/location}}
{{/highlights}}
{{/sections}}
```
