### ISSUE TITLE
Fail to upload a Kindle notes HTML file

### ISSUE THREAD

**Issue by tvhong** [pch/kindle-formatter#4]
Hi,
I encountered an issue when uploading the following Kindle notes HTML file to kindle-formatter: https://gist.github.com/tvhong/8249259d10e80c466c5e263e370c17ae .

Reproduction:
1. Save the above HTML file to local machine (e.g. hohpe2020.html)
2. Open https://kindle-formatter.com/
3. Open the browser's Developer Console
4. Upload the file hohpe2020.html to the website
5. Observe that nothing happens in the browser UI, but there is the following error message in the Developer Console:
```
Uncaught TypeError: s is null
    NextJS 16
index-18ee846dac5208b2.js:1:20583
    nP NextJS
    forEach self-hosted:203
    NextJS 15
        nP
        onload
    (Async: EventHandlerNonNull)
        d
        onDrop
        eU
        eH
        re
        re
        rn
        ro
        oN
        eO
        ro
        nU
        nD
```

Expected behavior: The tool should successfully accept the above file.

Please let me know if you need any additional details. And thank you for creating this tool :) .

**Comment by pch** [comment]
Fixed. Thanks for reporting!

**Comment by tvhong** [comment]
Thank you for the quick response! It works now : ) .
